<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>01-TS-E2E_Testing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b9f81aae-c6e9-4bf5-a529-4b11f9796ffb</testSuiteGuid>
   <testCaseLink>
      <guid>9d5d0139-c3fd-4c18-8f77-3d7403adef86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario/Website/Positive_Testing/01-TC-Registration_Succes</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6eba93e1-de30-4b3c-98dc-280f1c742ddf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/katalonData/validLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6eba93e1-de30-4b3c-98dc-280f1c742ddf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>159ad418-bc67-4ba5-9587-a9d6dd3d0a11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6eba93e1-de30-4b3c-98dc-280f1c742ddf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>870c83a7-e495-45ad-b549-d6472c4a09cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6eba93e1-de30-4b3c-98dc-280f1c742ddf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>repeat_pass</value>
         <variableId>193b63e7-da83-4200-a4f9-55325ac19b20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6eba93e1-de30-4b3c-98dc-280f1c742ddf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sequrity_question</value>
         <variableId>d057a79f-b65f-4f09-bea6-57dbde501cc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6eba93e1-de30-4b3c-98dc-280f1c742ddf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>answer_question</value>
         <variableId>94eaf1f5-1e6e-40f1-a44a-381ab6e40d9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51af1e84-7156-424f-b357-d7e97b539f35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario/Website/Positive_Testing/02-TC-Login_Success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bc637e62-cbaf-47ba-8d40-ba0046f013e4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/katalonData/validLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bc637e62-cbaf-47ba-8d40-ba0046f013e4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>62acf7c9-2462-40df-95eb-39b9c0644db0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bc637e62-cbaf-47ba-8d40-ba0046f013e4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>72bcf3e7-0bc2-47f6-b10f-2e2bdc675667</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
