<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>texttitle_Sign_in_with_Google</name>
   <tag></tag>
   <elementGuidId>4fab39be-a69c-496d-b966-a6ad698b6ee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yDmH0d']/c-wiz/div/div/c-wiz/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.WHUyzc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sign in with Google&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bdd35140-562b-45e5-8b92-0d9904373cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WHUyzc</value>
      <webElementGuid>5046476c-d43c-458d-b008-2f728f4dbdae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in with Google</value>
      <webElementGuid>c98c3ee0-7c52-4fc5-b260-a13e80813448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;A77ntc&quot;]/div[@class=&quot;Svhjgc&quot;]/div[@class=&quot;zIgDIc&quot;]/c-wiz[1]/div[@class=&quot;Wf6lSd&quot;]/div[@class=&quot;no7ij&quot;]/div[@class=&quot;WHUyzc&quot;]</value>
      <webElementGuid>d084fb5f-4214-43db-992a-adc37091c85b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/div/div/c-wiz/div/div/div[2]</value>
      <webElementGuid>ee480137-b354-4192-9941-fce050d74617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::div[1]</value>
      <webElementGuid>8326d9d0-06ed-4ba2-901e-f27f7a160078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in with Google']/parent::*</value>
      <webElementGuid>10339b3e-0faa-4916-b93a-df0082967e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//c-wiz/div/div/div[2]</value>
      <webElementGuid>61a28343-f0cd-47b7-a2be-638b97fc65de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign in with Google' or . = 'Sign in with Google')]</value>
      <webElementGuid>53c3622b-0725-4677-96fd-357eb2ed9ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
