<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Already_a_customer</name>
   <tag></tag>
   <elementGuidId>f9be1847-a94d-4bee-af0f-42b7cf6ace02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alreadyACustomerLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alreadyACustomerLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#alreadyACustomerLink</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f8c59a3-16ae-466c-9883-92dd3fc2bfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alreadyACustomerLink</value>
      <webElementGuid>b1eba759-728b-41ae-9828-fb56578bdfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Already a customer?</value>
      <webElementGuid>3739cdde-e4d8-4e69-bcc5-a6df7a667a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alreadyACustomerLink&quot;)</value>
      <webElementGuid>cc6994eb-0826-414a-afb4-ead340b5cd67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='alreadyACustomerLink']</value>
      <webElementGuid>10af740e-4d57-4cda-9074-da4c2c5bcfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/div[2]</value>
      <webElementGuid>46377759-967c-47c1-a0e5-19ca709ed539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='person_add'])[1]/following::div[1]</value>
      <webElementGuid>5e087abd-0f4b-4332-9bdf-ec8a8e6be2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open side menu'])[1]/preceding::div[3]</value>
      <webElementGuid>2f6a9f40-63fb-465b-bc66-61b635b542ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>96ec25d1-306c-41fb-9fa3-c04ab551256e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'alreadyACustomerLink' and (text() = 'Already a customer?' or . = 'Already a customer?')]</value>
      <webElementGuid>01853310-f062-45d1-9f4a-b48bdcdac381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
