<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_answerquestion</name>
   <tag></tag>
   <elementGuidId>6bb364a4-d27c-41d9-acca-58da2215d89e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securityAnswerControl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#securityAnswerControl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Answer to your security question&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4636a7b-7d19-4724-a07a-f480599440cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityAnswerControl</value>
      <webElementGuid>3ce4966b-7bc8-4513-9007-044e72cc121c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea32ca07-627c-43f7-b77b-9fe6e7a84482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Field for the answer to the security question</value>
      <webElementGuid>ab72173b-f450-4cce-8297-1720011f1033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-16 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>907b079b-d137-4924-8732-1d7b4baf4ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>c6246028-040e-4242-b834-162ba2263f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Answer to your security question</value>
      <webElementGuid>1bea850f-febe-471a-a2a0-c5d92653e88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12a5e150-bc13-4767-9da1-7d014c3fb955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityAnswerControl&quot;)</value>
      <webElementGuid>ba3a9fe0-b227-452e-a4f6-bd5aae9ed5eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityAnswerControl']</value>
      <webElementGuid>40096045-e3f5-4731-a429-b8f3445af025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>e9276130-82b8-463b-8c8a-c07930cf0f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>0c887b58-12e5-4ee9-b2b1-7e784c86af52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'securityAnswerControl' and @type = 'text' and @placeholder = 'Answer to your security question']</value>
      <webElementGuid>ec0210d9-3336-451b-9a23-4117f6a77b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
